FROM node:12-alphine3.11
LABEL version="1.0"
LABEL description="Development image for video subsrcop and streaming app"

WORKDIR /app


COPY ['package.json','package-lock.json*','npm-shrinkwarp.json*' , './']

RUN npm install && npm cache clean --force 


COPY . .


EXPOSE 5000 


cmd ['yarn' ,'start:dev']